name: Build

on:
  push:
    branches:
    - master
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - master

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: docker build --tag php-fpm .
