name: Dependencies
on:
  schedule:
  - cron: "30 2 * * *"
  workflow_dispatch:
jobs:
  updates:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Update dependencies
      run: |
        docker-compose -f "docker-compose.update.yml" up
        docker-compose -f "docker-compose.update.yml" down

    - name: Create PR
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: "chore(deps): update dependencies.json"
        branch: features/update-dependencies
        title: Update APT packages
        body: Updated dependencies.json
        labels: dependencies
        delete-branch: true
