name: Test
on:
  push:
    branches:
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - main
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: docker-compose -f docker-compose.test.yml up -d --build

    - name: Test
      run: |
        docker-compose -f docker-compose.test.yml exec -T test npm install --prefer-offline --no-audit --no-fund --no-update-notifier
        docker-compose -f docker-compose.test.yml exec -T test npm run test

    - name: Cleanup
      run: docker-compose -f docker-compose.test.yml down --volumes
      if: always()
