name: Test
on:
  push:
    branches:
    - main
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - main
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Build
      run: |
        docker-compose build src
        docker-compose up -d

    - name: Test
      run: |
        docker-compose exec -T test npm install --prefer-offline --no-audit --no-fund --no-update-notifier
        docker-compose exec -T test npm run test

    - name: Cleanup
      run: docker-compose down --volumes
      if: always()
